DEFAULT_TENT_SIZE = 16
DEFAULT_SOLVER_TYPE = "heuristic"
DEFAULT_GRAPH_TYPE = "circulant"
DEFAULT_HEURISTIC_MODE = "intelligent"
MAX_K_MULTIPLIER_DEFAULT = 20
GREEDY_ATTEMPTS_DEFAULT = 100 
DEFAULT_CIRCULANT_OFFSET = 5 