DEFAULT_TENT_SIZE = 8
DEFAULT_SOLVER_TYPE = "branch-and-bound"
DEFAULT_GRAPH_TYPE = "mongolian_tent"
DEFAULT_HEURISTIC_MODE = "intelligent"
MAX_K_MULTIPLIER_DEFAULT = 20
GREEDY_ATTEMPTS_DEFAULT = 100 
DEFAULT_CIRCULANT_OFFSET = 5 